services:
  spring-app:
    image: csw0302/springbootapp:1.3
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/capstone
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=30000
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=10
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,chrome-extension://*
      - SPRING_WEB_CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,chrome-extension://*
      - SPRING_WEB_CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS,PATCH
      - SPRING_WEB_CORS_ALLOWED_HEADERS=*
      - SPRING_WEB_CORS_ALLOW_CREDENTIALS=true
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network

  mariadb:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=capstone
      - MYSQL_ROOT_HOST=%
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - spring-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data: